---
application:
  name: "kolejperindu"
  project: "kolejperindu"
  organization: "QoveryCommunity"
  storage:
  - name: "public"
    size: "500"
    type: "hdd"
    mount_point: "./public"
databases:
- type: "MONGODB"
  name: "KolejPerindu"
  version: "4.4"
routers:
- name: "main-kolejperindu"
  routes:
  - application_name: "kolejperindu"
    paths:
    - "/*"
